### PR TITLE
Cleanup and update the project

### PR DESCRIPTION
**Pull request by BD103**
This adds a few smaller changes that makes `ferris-says` less dated.

- Migrates the base crate to the 2021 edition (31264573770110a8ccbc5dcdbf42d82e6ace857e)
- Fix incorrect version in the readme (ee49038b94f17b67c8a0d4fcea58c69b1939cc34)
- Update examples in readme and doctests (898bdf739aba5d1e9cd9c6e478fdd5e3da9e2001, c7486f06f5d68fef6c0a51bede63991a01f94603)
- Additional formatting
- Raise minimum required version of dependencies

### CODE REVIEW

**Comment by BD103** [comment]
@Amanieu would you mind reviewing this PR? If not, I can ping someone else on the `crate-maintainers` teams.

**Comment by lcnr** [comment]
Thank you for splitting your PR in self-contained commits, I very much appreciate it. :heart:

Your PR currently has merge conflicts and some of the commits are now unnecessary. It unfortunately needs a rebase.

**Comment by BD103** [comment]
> Thank you for splitting your PR in self-contained commits, I very much appreciate it. ❤️
> 
> Your PR currently has merge conflicts and some of the commits are now unnecessary. It unfortunately needs a rebase.

Ok, merge conflicts resolved! :)

**Comment by lcnr** [comment]
Thanks!

**Pull request merged**
