### PR TITLE
Use Ferris's preferred pronouns, and make the ASCII art more legible

### PR DESCRIPTION
**Pull request by federicomenaquintero**

### CODE REVIEW

**Comment by mgattozzi** [comment]
Hey thanks for this! In my presentation I tried to be gender neutral, then here I must have messed up.. My bad! Is there something where this was defined that Ferris is she/her? Otherwise it'd be better to default to they/them. That and updating the relevant documentation as well just and case

**Comment by federicomenaquintero** [comment]
See e.g. https://www.kickstarter.com/projects/1702984242/ferris-the-small-squishable-rustacean-rust-mascot?ref=thanks_link and grep for "make you happy".

**Comment by mgattozzi** [comment]
Thanks for these changes! :D

**Comment by federicomenaquintero** [comment]
Cool, thanks :)

**Pull request merged**
