### PR TITLE
Update clap to v4

### PR DESCRIPTION
**Pull request by dtolnay**

### CODE REVIEW

**Comment by lcnr** [comment]
This PR unfortunately needs a rebase due to https://github.com/rust-lang/ferris-says/pull/54

**Comment by dtolnay** [comment]
Rebased.

**Comment by lcnr** [comment]
Thanks! I appreciate it ❤️

*edit: looks like there's a new merge conflict* 😅

**Comment by dtolnay** [comment]
Indeed, it was the import for `PathBuf`. Fixed.

**Comment by lcnr** [comment]
Thanks!

**Pull request merged**
